### ISSUE TITLE
Loading diffusion model ... Error

### ISSUE THREAD

**Issue by shirleyanan** [TencentARC/InstantMesh#106]
Hello, I encountered the following error when running run.py during Loading diffusion model. Can you please tell me what the issue is?

Traceback (most recent call last):
  File "run.py", line 100, in <module>
    pipeline = DiffusionPipeline.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 932, in from_pretrained
    cached_folder = cls.download(
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 1349, in download
    info = model_info(
  File "/root/miniconda3/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1697, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sudo-ai/zero123plus-v1.2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff0fbb280a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))"), '(Request ID: bf6a5ab5-1431-489f-96eb-c3c35e4f8d72)')

**Comment by Sangrish-s** [comment]
Its an internet connection problem by the looks of it, maybe setup a timeout param if connection is slow
