### ISSUE TITLE
Docker - Unexpected error from cudaGetDeviceCount()

### ISSUE THREAD

**Issue by Zankaster** [TencentARC/InstantMesh#118]
I'm trying to run the docker image (since I wasn't able to install all the dependencies to run it on windows), after I build the image, I run it as the readme.md instructs but I get the following error. I'm on Windows 11 and I have a 4090:

Traceback (most recent call last):
  File "/workspace/instantmesh/app.py", line 101, in <module>
    pipeline = pipeline.to(device0)
  File "/workspace/miniconda3/envs/instantmesh/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 727, in to
    module.to(torch_device, torch_dtype)
  File "/workspace/miniconda3/envs/instantmesh/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2179, in to
    return super().to(*args, **kwargs)
  File "/workspace/miniconda3/envs/instantmesh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/workspace/miniconda3/envs/instantmesh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/workspace/miniconda3/envs/instantmesh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/workspace/miniconda3/envs/instantmesh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/workspace/miniconda3/envs/instantmesh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/workspace/miniconda3/envs/instantmesh/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/workspace/miniconda3/envs/instantmesh/lib/python3.10/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 500: named symbol not found

**Comment by Innary** [comment]
I think you should update your docker desktop version >4.34.x
