### ISSUE TITLE
An error occurs when running app.py

### ISSUE THREAD

**Issue by XuanTian-LTD** [TencentARC/InstantMesh#161]
Seed set to 0
Loading diffusion model ...
Couldn't connect to the Hub: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sudo-ai/zero123plus-v1.2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B1A2358A90>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: a4ca03f2-7a67-41e3-a2ca-6a22bb6042fe)').
Will try to load from local cache.
Loading pipeline components...: 100%|██████████| 8/8 [00:01<00:00,  6.00it/s]
Loading reconstruction model ...
D:\Program Files\JetBrains\Venv\InstantMesh\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Some weights of ViTModel were not initialized from the model checkpoint at facebook/dino-vitb16 and are newly initialized: ['encoder.layer.0.adaLN_modulation.1.bias', 'encoder.layer.0.adaLN_modulation.1.weight', 'encoder.layer.1.adaLN_modulation.1.bias', 'encoder.layer.1.adaLN_modulation.1.weight', 'encoder.layer.10.adaLN_modulation.1.bias', 'encoder.layer.10.adaLN_modulation.1.weight', 'encoder.layer.11.adaLN_modulation.1.bias', 'encoder.layer.11.adaLN_modulation.1.weight', 'encoder.layer.2.adaLN_modulation.1.bias', 'encoder.layer.2.adaLN_modulation.1.weight', 'encoder.layer.3.adaLN_modulation.1.bias', 'encoder.layer.3.adaLN_modulation.1.weight', 'encoder.layer.4.adaLN_modulation.1.bias', 'encoder.layer.4.adaLN_modulation.1.weight', 'encoder.layer.5.adaLN_modulation.1.bias', 'encoder.layer.5.adaLN_modulation.1.weight', 'encoder.layer.6.adaLN_modulation.1.bias', 'encoder.layer.6.adaLN_modulation.1.weight', 'encoder.layer.7.adaLN_modulation.1.bias', 'encoder.layer.7.adaLN_modulation.1.weight', 'encoder.layer.8.adaLN_modulation.1.bias', 'encoder.layer.8.adaLN_modulation.1.weight', 'encoder.layer.9.adaLN_modulation.1.bias', 'encoder.layer.9.adaLN_modulation.1.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\Venv\InstantMesh\lib\site-packages\torch\utils\cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "D:\Program Files\JetBrains\Python\Python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\PythonProject\InstantMesh\app.py", line 113, in <module>
    model.init_flexicubes_geometry(device1, fovy=30.0)
  File "E:\PythonProject\InstantMesh\src\models\lrm_mesh.py", line 79, in init_flexicubes_geometry
    renderer = NeuralRender(device, camera_model=camera)
  File "E:\PythonProject\InstantMesh\src\models\geometry\render\neural_render.py", line 73, in __init__
    self.ctx = dr.RasterizeCudaContext(device=device)
  File "D:\Program Files\JetBrains\Venv\InstantMesh\lib\site-packages\nvdiffrast-0.3.2-py3.10.egg\nvdiffrast\torch\ops.py", line 185, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeCRStateWrapper(cuda_device_idx)
  File "D:\Program Files\JetBrains\Venv\InstantMesh\lib\site-packages\nvdiffrast-0.3.2-py3.10.egg\nvdiffrast\torch\ops.py", line 126, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=common_opts+cc_opts, extra_cuda_cflags=common_opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "D:\Program Files\JetBrains\Venv\InstantMesh\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "D:\Program Files\JetBrains\Venv\InstantMesh\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\Program Files\JetBrains\Venv\InstantMesh\lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\Program Files\JetBrains\Venv\InstantMesh\lib\site-packages\torch\utils\cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin': [1/1] "D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64/link.exe" Buffer.o CudaRaster.o RasterImpl.cuda.o RasterImpl.o common.o rasterize.cuda.o interpolate.cuda.o texture.cuda.o texture.o antialias.cuda.o torch_bindings.o torch_rasterize.o torch_interpolate.o torch_texture.o torch_antialias.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib "/LIBPATH:D:\Program Files\JetBrains\Venv\InstantMesh\lib\site-packages\torch\lib" torch_python.lib "/LIBPATH:D:\Program Files\JetBrains\Venv\InstantMesh\Scripts\libs" "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib\x64" cudart.lib /out:nvdiffrast_plugin.pyd
FAILED: nvdiffrast_plugin.pyd 
"D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64/link.exe" Buffer.o CudaRaster.o RasterImpl.cuda.o RasterImpl.o common.o rasterize.cuda.o interpolate.cuda.o texture.cuda.o texture.o antialias.cuda.o torch_bindings.o torch_rasterize.o torch_interpolate.o torch_texture.o torch_antialias.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib "/LIBPATH:D:\Program Files\JetBrains\Venv\InstantMesh\lib\site-packages\torch\lib" torch_python.lib "/LIBPATH:D:\Program Files\JetBrains\Venv\InstantMesh\Scripts\libs" "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib\x64" cudart.lib /out:nvdiffrast_plugin.pyd

ninja: build stopped: subcommand failed.

Any solutions there?
VS2017
CUDA11.3

**Comment by David-655** [comment]
Hi bro, I meet the same problem, did you solve it?
