### ISSUE TITLE
Does anyone check if installation works regularly?

### ISSUE THREAD

**Issue by grandmazboy** [TencentARC/InstantMesh#178]
I mean does it hurt to update the requirements.txt with exact versions.. since you wont know when a package is updated and if its compatible with other versions.
Does anyone ever compile code to work with newer versions of Cuda, Python or VS?

Seems like stable diffusion and other tools similar to this finish something then just give up on maintaining.

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
texture.cu
ninja: build stopped: subcommand failed.

VS Build Tools 2022 17.12.2 / 14.42.34433
VS Professional 2022 14.29.30133
Desktop development with C++  / tried both MSVC v142/143
Cuda 12.1
Python 3.10
Windows 11 / Not using Conda
Nvidia RTX 4080

(venv) PS E:\InstantMesh-main> python run.py configs/instant-mesh-large.yaml examples/bird.jpg --save_video --no_rembg
Seed set to 42
Loading diffusion model ...
Loading pipeline components...:  12%|██████▌                                             | 1/8 [00:00<00:00,  7.82it/s]The config attributes {'dropout': 0.0, 'reverse_transformer_layers_per_block': None} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 8/8 [00:01<00:00,  6.42it/s]
Loading custom white-background unet ...
Loading reconstruction model ...
Some weights of ViTModel were not initialized from the model checkpoint at facebook/dino-vitb16 and are newly initialized: ['encoder.layer.7.adaLN_modulation.1.bias', 'encoder.layer.6.adaLN_modulation.1.weight', 'encoder.layer.4.adaLN_modulation.1.bias', 'encoder.layer.0.adaLN_modulation.1.weight', 'encoder.layer.6.adaLN_modulation.1.bias', 'encoder.layer.1.adaLN_modulation.1.bias', 'encoder.layer.10.adaLN_modulation.1.bias', 'encoder.layer.2.adaLN_modulation.1.weight', 'encoder.layer.7.adaLN_modulation.1.weight', 'encoder.layer.9.adaLN_modulation.1.weight', 'encoder.layer.3.adaLN_modulation.1.weight', 'encoder.layer.2.adaLN_modulation.1.bias', 'encoder.layer.8.adaLN_modulation.1.weight', 'encoder.layer.11.adaLN_modulation.1.bias', 'encoder.layer.8.adaLN_modulation.1.bias', 'encoder.layer.5.adaLN_modulation.1.bias', 'encoder.layer.3.adaLN_modulation.1.bias', 'encoder.layer.5.adaLN_modulation.1.weight', 'encoder.layer.9.adaLN_modulation.1.bias', 'encoder.layer.10.adaLN_modulation.1.weight', 'encoder.layer.4.adaLN_modulation.1.weight', 'encoder.layer.1.adaLN_modulation.1.weight', 'encoder.layer.11.adaLN_modulation.1.weight', 'encoder.layer.0.adaLN_modulation.1.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "E:\InstantMesh-main\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "C:\Program Files\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\InstantMesh-main\run.py", line 132, in <module>
    model.init_flexicubes_geometry(device, fovy=30.0)
  File "E:\InstantMesh-main\src\models\lrm_mesh.py", line 79, in init_flexicubes_geometry
    renderer = NeuralRender(device, camera_model=camera)
  File "E:\InstantMesh-main\src\models\geometry\render\neural_render.py", line 73, in __init__
    self.ctx = dr.RasterizeCudaContext(device=device)
  File "E:\InstantMesh-main\venv\lib\site-packages\nvdiffrast\torch\ops.py", line 184, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeCRStateWrapper(cuda_device_idx)
  File "E:\InstantMesh-main\venv\lib\site-packages\nvdiffrast\torch\ops.py", line 125, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=common_opts+cc_opts, extra_cuda_cflags=common_opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "E:\InstantMesh-main\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "E:\InstantMesh-main\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\InstantMesh-main\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "E:\InstantMesh-main\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e

**Comment by grandmazboy** [comment]
I have uninstalled Python and moved to 3.10.6 and separately installed StableDiffusion and its working . I am getting a shyt ton of package dependancy conflicts and one that always pops up is huggingface_hub

**Comment by Darth-Carrotpie** [comment]
Check https://github.com/TencentARC/InstantMesh/issues/175#issuecomment-2495631712
If it's a problem in a Dockerfile, which should be stable in theory, it's gonna be even a bigger problem in regular installs...
In the end I did run it via docker, but when generating a mesh it errored out without any message. Not sure where to go on after that :/

**Comment by grandmazboy** [comment]
I tried on a different computer today, with just the bare minimum of 3.10, visual studio community 2022, build tools, cuda 12.1 etc and that is getting very similar errors to what I'm getting on this PC. I suspect mass package dependency version issues just don't know the right combo..

**Comment by SoftologyPro** [comment]
I also cannot get a working set of packages any more.
Can someone please provide an updated requirements.txt with exact versions?

**Comment by xazds** [comment]
huggingface_hub引起各种冲突，组合了一晚上也没能解决

**Comment by zrichz** [comment]
I agree that this repo is *full* of inaccuracies/mismatches/omissions and outdated :(
