### ISSUE TITLE
Could not locate the pipeline.py inside zero123plus.

### ISSUE THREAD

**Issue by yetiiil** [TencentARC/InstantMesh#26]
Hi, when I tried to run the code, I received the following issue. I think the problem comes from here:

pipeline = DiffusionPipeline.from_pretrained(
    "sudo-ai/zero123plus-v1.2", 
    custom_pipeline="zero123plus",
    torch_dtype=torch.float16,
    cache="/scratch/huggingface"
)
Do you know if it is a problem linked with InstantMesh or Huggingface?

Could not locate the pipeline.py inside zero123plus.
Traceback (most recent call last):
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/huggingface/diffusers/v0.27.2/examples/community/zero123plus.py

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch2/yuxili/interiorDesign/InstantMesh/run_instantmesh.py", line 98, in <module>
    pipeline = DiffusionPipeline.from_pretrained(
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 671, in from_pretrained
    cached_folder = cls.download(
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1317, in download
    pipeline_class = _get_pipeline_class(
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 323, in _get_pipeline_class
    return get_class_from_dynamic_module(
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 441, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 287, in get_cached_module_file
    resolved_module_file = cached_download(
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 697, in cached_download
    r = _request_wrapper(
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 369, in _request_wrapper
    response = _request_wrapper(
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 393, in _request_wrapper
    hf_raise_for_status(response)
  File "/scratch2/yuxili/miniconda3/envs/env_test_test/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 371, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/huggingface/diffusers/v0.27.2/examples/community/zero123plus.py

**Comment by yetiiil** [comment]
After I reinstalled diffusers and huggingface-hub, transformers, the problem still exists: huggingface_hub.utils._errors.HfHubHTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/huggingface/diffusers/v0.20.2/examples/community/zero123plus.py

**Comment by bluestyle97** [comment]
You are running `run_instantmesh.py` instead of `run.py` Did you modify the code? What about deleting `cache="/scratch/huggingface"`?

**Comment by yetiiil** [comment]
The issue comes from running the code outside of InstantMesh folder, it has nothing to do with the files inside the folder, thanks!

**Comment by taeyeopl** [comment]
@yetiiil Did you solve the issue? I also faced the same issue if I put the code outside of the folder.

**Comment by taeyeopl** [comment]
I solved the problem by changing the directory. 

```
custom_dir = "InstantMesh/zero123plus"
pipeline = DiffusionPipeline.from_pretrained(
    "sudo-ai/zero123plus-v1.2",
    custom_pipeline=custom_dir,
    torch_dtype=torch.float16,
    )
```
