### ISSUE TITLE
编译中断

### ISSUE THREAD

**Issue by huahai2022** [TencentARC/InstantMesh#36]
/home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/torch/include/torch/csrc/profiler/util.h:34:10: 致命错误：x86intrin.h：No such file or directory
   34 | #include <x86intrin.h>
      |          ^~~~~~~~~~~~~
编译中断。
ninja: build stopped: subcommand failed.

**Comment by bluestyle97** [comment]
We cannot provide any help since there is not enough information.

**Comment by huahai2022** [comment]
Traceback (most recent call last):
  File "/home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "/home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.


RuntimeError: Error building extension 'nvdiffrast_plugin': [1/11] c++ -MMD -MF common.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/torch/include -isystem /home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/torch/include/TH -isystem /home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/torch/include/THC -isystem /home/zhangzhilong/tools/anaconda/envs/instantmesh/include -isystem /home/zhangzhilong/tools/anaconda/envs/instantmesh/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/nvdiffrast/common/common.cpp -o common.o 
FAILED: common.o 

In file included from /home/zhangzhilong/tools/anaconda/envs/instantmesh/include/driver_types.h:83,
                 from /home/zhangzhilong/tools/anaconda/envs/instantmesh/include/builtin_types.h:59,
                 from /home/zhangzhilong/tools/anaconda/envs/instantmesh/include/cuda_runtime.h:90,
                 from /home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/nvdiffrast/common/common.cpp:9:
/usr/include/limits.h:124:26: 错误：没有包含路径可供搜索 limits.h

感谢解答

**Comment by huahai2022** [comment]
Traceback (most recent call last):
  File "/home/zhangzhilong/project/instantmesh/InstantMesh/app.py", line 101, in <module>
    model.init_flexicubes_geometry(device, fovy=30.0)
  File "/home/zhangzhilong/project/instantmesh/InstantMesh/src/models/lrm_mesh.py", line 79, in init_flexicubes_geometry
    renderer = NeuralRender(device, camera_model=camera)
  File "/home/zhangzhilong/project/instantmesh/InstantMesh/src/models/geometry/render/neural_render.py", line 73, in __init__
    self.ctx = dr.RasterizeCudaContext(device=device)
  File "/home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 177, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeCRStateWrapper(cuda_device_idx)
  File "/home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "/home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "/home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/zhangzhilong/tools/anaconda/envs/instantmesh/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e



if IS_FLEXICUBES:
    model.init_flexicubes_geometry(device, fovy=30.0)我定位到了这行代码出错
感谢解答
