### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer?

### ISSUE THREAD

**Issue by TzyTman** [TencentARC/InstantMesh#45]
Loading diffusion model ...
Fetching 16 files:  31%|███████████████████████▏                                                  | 5/16 [00:00<00:01,  5.84it/s]
Traceback (most recent call last):
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mk/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/mk/.local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mk/InstantMesh-main/app.py", line 75, in <module>
    pipeline = DiffusionPipeline.from_pretrained(
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 932, in from_pretrained
    cached_folder = cls.download(
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1507, in download
    cached_folder = snapshot_download(
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 239, in snapshot_download
    thread_map(
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 214, in _inner_hf_hub_download
    return hf_hub_download(
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1431, in hf_hub_download
    http_get(
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 515, in http_get
    r = _request_wrapper(
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 452, in _request_wrapper
    return http_backoff(
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 258, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "/home/mk/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mk/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/mk/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/home/mk/.local/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: 0a2fe285-3285-4aa0-8e75-80deb64f22d2)')

**Comment by moonsliu** [comment]
It's probably a network problem.

**Comment by TzyTman** [comment]
> 这可能是网络问题。
Problem solved. Thank you.
