### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute '_str'

### ISSUE THREAD

**Issue by hgftrdw45ud67is8o89** [TencentARC/InstantMesh#73]
here is the error,I dont know how to solve please help,I dont know if its diffusers library problem or here,can somehow help debug?
```
Seed set to 42
Loading diffusion model ...
Traceback (most recent call last):
  File "D:\actpydevenv\Python311\Lib\pathlib.py", line 540, in __str__
    return self._str
           ^^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute '_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ai\img_proc\InstantMesh-main\run.py", line 114, in <module>
    pipeline = DiffusionPipeline.from_pretrained("sudo-ai/zero123plus-v1.2",custom_pipeline="zero123plus",torch_dtype=usertorchdtype)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\actpydevenv\Pyaivenv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
```

**Comment by bluestyle97** [comment]
Did you modify the `run.py`? It looks different from our official code.

**Comment by hgftrdw45ud67is8o89** [comment]
yeah,i added code to auto detect gpu type and use the best torch float type,because some gpu i have cannot support float16.

**Comment by bluestyle97** [comment]
I'm sorry but we did not test the code in Windows environment and the provided traceback does not provide enough information.

**Comment by hgftrdw45ud67is8o89** [comment]
I see its fine, I also have no idea,I will just close this issue and give up trying for now,maybe comeback a few months later and see.
