### ISSUE TITLE
TypeError: _native_multi_head_attention(): argument 'qkv_bias' (position 7) must be Tensor, not NoneType

### ISSUE THREAD

**Issue by Zhaohx424** [TencentARC/InstantMesh#8]
Traceback (most recent call last):
  File "/InstantMesh/run.py", line 213, in <module>
    planes = model.forward_planes(images, input_cameras)
  File "/InstantMesh/src/models/lrm_mesh.py", line 98, in forward_planes
    planes = self.transformer(image_feats)
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/InstantMesh/src/models/decoder/transformer.py", line 115, in forward
    x = layer(x, image_feats)
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/InstantMesh/src/models/decoder/transformer.py", line 65, in forward
    x = x + self.self_attn(before_sa, before_sa, before_sa)[0]
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1144, in forward
    return torch._native_multi_head_attention(
TypeError: _native_multi_head_attention(): argument 'qkv_bias' (position 7) must be Tensor, not NoneType

Do you know what's wrong with this problem? can anyone help me?

**Comment by bluestyle97** [comment]
@Zhaohx424 Hi, what pytorch version and xformers version are you using? We suggest using `pytorch>=2.1.0` and `xformers>= 0.0.22.post7`, otherwise there might be errors in the attention layer. I remember I met this problem before, which should be solved by upgrading the pytorch version.

**Comment by Zhaohx424** [comment]
> @Zhaohx424 Hi, what pytorch version and xformers version are you using? We suggest using `pytorch>=2.1.0` and `xformers>= 0.0.22.post7`, otherwise there might be errors in the attention layer. I remember I met this problem before, which should be solved by upgrading the pytorch version.

Thanks! It resolved my problem by upgrading PyTorch version from 2.0.1 to 2.1.0.
